kind: pipeline
name: mon-pipeline-ci
environment:
  BASE_URL: preact-hugo/

steps:
  - name: preact-cli
    image: lowess/preact-cli
    commands:
      - preact create ${DRONE_REPO}#${DRONE_COMMIT} test-ci
      - cd test-ci
      - npm install
      - npm run build
  - name: publish
    image: plugins/gh-pages
    settings:
      username: CyrilBochet
      password:
        from_secret: PW_GH
      pages_directory: test-ci/dist
  - name: notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: SLACK_WEBHOOKS
        channel: drone-ci
        link_names: true
        template: >
          {{#success build.status}}✔{{ else }}✘{{/success}} {{ uppercasefirst build.status }}*: <https://github.com/{{ repo.owner }}/{{ repo.name }}/pull/{{ build.pull }}|Pull Request #{{ build.pull }}>
          Commit: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}>
          Branch: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}>
          Author: {{ build.author }}
          <{{ build.link }}|Visit build page ↗>