kind: pipeline
name: mon-pipeline-ci

steps:
  - name: preact-cli
    image: lowess/preact-cli
    commands:
      - preact create ${DRONE_REPO}#${DRONE_COMMIT} test-ci
      - cd test-ci
      - npm install
      - npm run build

notify:
  image: plugins/slack
  channel: drone-ci
  webhook:
    from_secret: SLACK_WEBHOOKS
  template: >
    {{#if build.pull }}
      *{{#success build.status}}✔{{ else }}✘{{/success}} {{ uppercasefirst build.status }}*: <https://github.com/{{ repo.owner }}/{{ repo.name }}/pull/{{ build.pull }}|Pull Request #{{ build.pull }}>
    {{else}}
      *{{#success build.status}}✔{{ else }}✘{{/success}} {{ uppercasefirst build.status }}: Build #{{ build.number }}* (type: `{{ build.event }}`)
    {{/if}}
    Commit: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}>
    Branch: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}>
    Author: {{ build.author }}
    <{{ build.link }}|Visit build page ↗>